### ISSUE TITLE
new to this (Please help)

### ISSUE THREAD

**Issue by Mavrick007** [wvdumper/dumper#14]
hey im new how do i get this to extract keys from my huawei p30 pro please thanks, please explain what i need to do thanks

**Comment by pythonkenyard** [comment]
hmm your phone should be compatible for sure.    
readme tells you what you need.

Usage
Enable USB debugging
Start frida-server on the device (**you need root)**
Execute dump_keys.py
Start streaming some DRM-protected content

**Comment by Mavrick007** [comment]
how do i root my phone it please? so far im up to this part: adb.exe: no devices/emulators found , adb: error: failed to get feature set: more than one device/emulator

i got this when trying to root my phone

DC - Unlocker 2 Client 1.00.1436

Detecting phone :

selection :
manufacturer - Huawei phones
model - Auto detect (recommended)

Found Applications port COM6

This phone cannot be serviced with DC Unlocker, but may be supported in Test Point (software or hardware) by HCU software, check https://hcu-client.com/category/tutorials

**Comment by pythonkenyard** [comment]
Google how to do it. You need specific method for phone probably.
There's normally not a 1 click app. I spent 3hr today doing it again

**Comment by VCDEV1** [comment]
> how do i root my phone it please? so far im up to this part: adb.exe: no devices/emulators found , adb: error: failed to get feature set: more than one device/emulator
> 
> i got this when trying to root my phone
> 
> DC - Unlocker 2 Client 1.00.1436
> 
> Detecting phone :
> 
> selection : manufacturer - Huawei phones model - Auto detect (recommended)
> 
> Found Applications port COM6
> 
> This phone cannot be serviced with DC Unlocker, but may be supported in Test Point (software or hardware) by HCU software, check https://hcu-client.com/category/tutorials

what is your processor, android version, model?

**Comment by Mavrick007** [comment]
appently it cant be done, does this tool work for grabbing l1 cdm, keys etc from android devices? my device is VOG-L09, Version 10

**Comment by pythonkenyard** [comment]
Afaik no only L3 as mine errored  and in the readme he mentioned forcing l3

**Comment by Mavrick007** [comment]
> Afaik no only L3 as mine errored and in the readme he mentioned forcing l3

mine to my phone is saying root access is not properly installed on this device

**Comment by Mavrick007** [comment]
what do i need to do in order to get my phone rooted i tried everything

**Comment by pythonkenyard** [comment]
Go to a phone specific forum. You won't find answers here. Xda developers is usually good for rooting solutions

**Comment by Mavrick007** [comment]
> Xda developers

i got the app kingroot installed now but its still on 01% taking ages to go past it but its Acquiring Root it says, does that mean its working propley?

**Comment by Amb33r** [comment]
@pythonkenyard 
> 
 Usage
 Enable USB debugging - **OK DONE** 

 Start frida-server on the device (**you need root)** - **OK DONE** 
![Screenshot_20211219-165716](https://user-images.githubusercontent.com/70627077/146681815-6cc38c4c-cb09-4bdd-9452-039daabb4825.png)

Execute dump_keys.py - **where to run on pc or iphone?**  py dump_keys.py 
run pc 
![image](https://user-images.githubusercontent.com/70627077/146682015-d23d73d5-98e5-497c-867c-0a585dc09cf3.png)

Start streaming some DRM-protected content -**where to run on pc or iphone?**  
np https://bitmovin.com/demos/drm ??

**Comment by pythonkenyard** [comment]
It's not detecting your phone.

You need to enable USB debugging and when you connect phone to computer you usually need to select some option on phone saying ok to debug or connect or something.

To test You can run "adb devices"    
In terminal after it's connected and you enabled USB debugging to confirm it's connected.     

It outputs "device XYZ"

You are v close though for sure it seems.

**Comment by Amb33r** [comment]
![image](https://user-images.githubusercontent.com/70627077/146682362-e3aaaaf0-a675-4aa1-9ecc-3011583b19ca.png)

**Comment by Mavrick007** [comment]
hey guys so i want to buy [URL="https://www.amazon.co.uk/gp/product/B07F9K51DV/ref=ewc_pr_img_1?smid=A143L92HUPXV5W&psc=1"]T95 S1 Android TV BOX, Android 7.1 Amlogic S905W Quad Core 2GB/16GB with Digital Display HD Ultra HD 4K Ethernet 2.4GHz Wifi H.265 Video Decoder[/URL], how would i go about rooting it and dumping the l3 cdm from it please? i need step by step video tutorial (via DM) on how to get [URL="https://github.com/wvdumper/dumper"]Dumper[/URL] to dump the l3 cdm and keys etc thanks, does anyone else have T95 S1 Android TV BOX, Android 7.1 Amlogic S905W Quad Core 2GB/16GB with Digital Display HD Ultra HD 4K Ethernet 2.4GHz Wifi H.265 Video Decoder and have you managed to dump l3 keys from this device using dumper??

python dump_keys.py
Traceback (most recent call last):
  File "dump_keys.py", line 14, in <module>
    device = frida.get_usb_device()
  File "C:\Users\Maverick\AppData\Roaming\Python\Python36\site-packages\frida\__init__.py", line 89, in get_usb_device
    return get_device_matching(lambda d: d.type == 'usb', timeout, **kwargs)
  File "C:\Users\Maverick\AppData\Roaming\Python\Python36\site-packages\frida\__init__.py", line 97, in get_device_matching
    return get_device_manager().get_device_matching(predicate, timeout, **kwargs)
  File "C:\Users\Maverick\AppData\Roaming\Python\Python36\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Maverick\AppData\Roaming\Python\Python36\site-packages\frida\core.py", line 58, in get_device_matching
    return Device(self._impl.get_device_matching(lambda d: predicate(Device(d)), raw_timeout))
frida.InvalidArgumentError: device not found
