### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by projectnaked** [wvdumper/dumper#17]
Hi can someone help me with this im getting the error

C:\Users\user\Desktop\dumper-main>python dump_keys.py
2021-12-20 03:57:54 PM - root - 16 - INFO - Connected to SM N9005
2021-12-20 03:57:54 PM - root - 17 - INFO - scanning all processes for the following libraries
Traceback (most recent call last):
  File "C:\Users\user\Desktop\dumper-main\dump_keys.py", line 18, in <module>
    for process in device.enumerate_processes():
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\frida\core.py", line 110, in enumerate_processes
    return self._impl.enumerate_processes(*args, **kwargs)
frida.ServerNotRunningError: unable to connect to remote frida-server: closed

**Comment by JD906** [comment]
The error is in the last line.
frida.ServerNotRunning

**Comment by projectnaked** [comment]
> The error is in the last line. frida.ServerNotRunning

it is running i tried many versions every time i got same error

**Comment by cimbor** [comment]
Same here on Samsung Galaxy Note 4, using magisk Frida I'm able to list process with frida-ps -U but dumper fails to attach.

**Comment by projectnaked** [comment]
i fixed it by changing the rom to lineage os 18.1 and using magisk as root

**Comment by cimbor** [comment]
> i fixed it by changing the rom to lineage os 18.1 and using magisk as root

that's Android 11; it is working there this tool?

**Comment by projectnaked** [comment]
> > i fixed it by changing the rom to lineage os 18.1 and using magisk as root
> 
> that's Android 11; it is working there this tool?

yes its work i got the keys and id changed the nfripper cdm and now its work

**Comment by tuprimafromtomelloso** [comment]
how did you manage it to work? whats your cdm version?

cant get pass of "57 - DEBUG - processing id"

thx

**Comment by projectnaked** [comment]
> how did you manage it to work? whats your cdm version?
> 
> cant get pass of "57 - DEBUG - processing id"
> 
> thx

yes i get it work and the cdm is L3 it is working with nfripper

**Comment by tuprimafromtomelloso** [comment]
yes but how?

**Comment by projectnaked** [comment]
> yes but how?

rooted the device with magisk and installed the magisk frida server and installed liboemcrypto-disabler-master 
at first i got frida device not found so i changed this in the script device = frida.get_usb_device() to this device = frida.get_usb_device(1) found the device hooked up after that played something on the netflix app i got the client_id and private_key

**Comment by tuprimafromtomelloso** [comment]
thx but like you can see i can run the script but it just hangs at "57 - DEBUG - processing id".

Lineage OS 18.1, Magisk root, liboemcrypto-disabler, magisk-frida. cdm version 16.0.

I get the keybox but not the rest of the keys.
