### ISSUE TITLE
frida.core.RPCException: ReferenceError: 'TextEncoder' is not defined

### ISSUE THREAD

**Issue by CHDWEB** [wvdumper/dumper#2]
2021-12-02 01:37:43 PM - root - 17 - INFO - scanning all processes for the following libraries
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=1, name="init", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=523, name="init", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=524, name="init", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=525, name="ueventd", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=547, name="logd", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=548, name="qseecomd", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=549, name="android.hardware.keymaster@4.0-service-qti", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=566, name="vold", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=567, name="hwservicemanager", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=582, name="servicemanager", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=583, name="vndservicemanager", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=584, name="android.hardware.gatekeeper@1.0-service-qti", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=637, name="netd", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=638, name="zygote64", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=639, name="zygote", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=646, name="iptables-restore", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=647, name="ip6tables-restore", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=697, name="sscrpcd", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=698, name="android.hardware.audio@2.0-service", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=699, name="android.hidl.allocator@1.0-service", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=700, name="healthd", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=701, name="android.hardware.bluetooth@1.0-service-qti", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=702, name="android.hardware.camera.provider@2.4-service_64", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=703, name="android.hardware.cas@1.0-service", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=704, name="android.hardware.configstore@1.1-service", parameters={})
2021-12-02 01:37:43 PM - root - 19 - DEBUG - Process(pid=705, name="android.hardware.drm@1.0-service", parameters={})
Traceback (most recent call last):
  File "C:\Users\summe\Downloads\Compressed\dumper-main\dumper-main\dump_keys.py", line 24, in <module>
    scanner.hook_to_process(device, process.name, library)
  File "C:\Users\summe\Downloads\Compressed\dumper-main\dumper-main\Helpers\Scanner.py", line 168, in hook_to_process
    script.exports.inject(library, process)
  File "C:\Users\summe\AppData\Roaming\Python\Python39\site-packages\frida\core.py", line 468, in method
    return script._rpc_request('call', js_name, args, **kwargs)
  File "C:\Users\summe\AppData\Roaming\Python\Python39\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\summe\AppData\Roaming\Python\Python39\site-packages\frida\core.py", line 400, in _rpc_request
    raise result[2]
frida.core.RPCException: ReferenceError: 'TextEncoder' is not defined
    at sender_payload_info (/script1.js:781)
    at inject (/script1.js:29)
    at apply (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:13)
    at c (frida/runtime/message-dispatcher.js:23)

Hi,buddy,may I ask how to fix this?
thank you~

**Comment by antoine-lombardo** [comment]
same here
