### ISSUE TITLE
help plz

### ISSUE THREAD

**Issue by Mavrick007** [wvdumper/dumper#26]
so i have my T95 S1 Android TV BOX device, connected to home wifi not pc wifi, pc connected to wifi and downloaded frida server and installed and its running on the T95 And its rooted, im getting

Traceback (most recent call last):
File "C:\Users\Username\Desktop\Use for rooting & grabbing l3 cdm from android tv box\Dumper\dump_keys.py", line 21, in <module>
libraries = scanner.find_widevine_process(device, process.name)
File "C:\Users\Username\Desktop\Use for rooting & grabbing l3 cdm from android tv box\Dumper\Helpers\Scanner.py", line 149, in find_widevine_process
process = dev.attach(process_name)
File "C:\Users\Username\AppData\Roaming\Python\Pyth on39 \site-packages\frida\core.py", line 26, in wrapper
return f(*args, **kwargs)
File "C:\Users\Username\AppData\Roaming\Python\Pyth on39 \site-packages\frida\core.py", line 165, in attach
return Session(self._impl.attach(self._pid_of(target), *args, **kwargs))
frida.ProcessNotRespondingError: process with pid 12228 either refused to load frida-agent, or terminated during injection

C:\Users\Username\Desktop\Use for rooting & grabbing l3 cdm from android tv box\Dumper>pause
Press any key to continue . . .

UPDATE...

IM GETTING:

2021-12-28 09:54:43 PM - root - 25 - INFO - Hooks completed

UPDATE 2: 
only thing is the android tv box wont load any apps, websites or anything now

UPDATE 3:
playing netflix movie in chrome and only getting:
2021-12-28 09:54:43 PM - root - 25 - INFO - Hooks completed

please help thanks

**Comment by VCDEV1** [comment]
> so i have my T95 S1 Android TV BOX device, connected to home wifi not pc wifi, pc connected to wifi and downloaded frida server and installed and its running on the T95 And its rooted, im getting
> 
> Traceback (most recent call last): File "C:\Users\Username\Desktop\Use for rooting & grabbing l3 cdm from android tv box\Dumper\dump_keys.py", line 21, in libraries = scanner.find_widevine_process(device, process.name) File "C:\Users\Username\Desktop\Use for rooting & grabbing l3 cdm from android tv box\Dumper\Helpers\Scanner.py", line 149, in find_widevine_process process = dev.attach(process_name) File "C:\Users\Username\AppData\Roaming\Python\Pyth on39 \site-packages\frida\core.py", line 26, in wrapper return f(*args, **kwargs) File "C:\Users\Username\AppData\Roaming\Python\Pyth on39 \site-packages\frida\core.py", line 165, in attach return Session(self._impl.attach(self._pid_of(target), *args, **kwargs)) frida.ProcessNotRespondingError: process with pid 12228 either refused to load frida-agent, or terminated during injection
> 
> C:\Users\Username\Desktop\Use for rooting & grabbing l3 cdm from android tv box\Dumper>pause Press any key to continue . . .
> 
> UPDATE...
> 
> IM GETTING:
> 
> 2021-12-28 09:54:43 PM - root - 25 - INFO - Hooks completed
> 
> UPDATE 2: only thing is the android tv box wont load any apps, websites or anything now
> 
> UPDATE 3: playing netflix movie in chrome and only getting: 2021-12-28 09:54:43 PM - root - 25 - INFO - Hooks completed
> 
> please help thanks

@Mavrick007 Bro did you fix it. I also orderd this box should I cancel it. Or is it working

**Comment by t33v33b0x** [comment]
![Untitled](https://user-images.githubusercontent.com/96581227/147672092-db347a94-c305-4321-abb0-535bb28a3eb2.png)
Keys dumped from that box for me fine. Box was pre-rooted, ADB connect via WiFi, used the Frida Server app from the Play Store. Can't remember for sure but I think I played back DRM in the Netflix app

**Comment by Mavrick007** [comment]
> ![Untitled](https://user-images.githubusercontent.com/96581227/147672092-db347a94-c305-4321-abb0-535bb28a3eb2.png) Keys dumped from that box for me fine. Box was pre-rooted, ADB connect via WiFi, used the Frida Server app from the Play Store. Can't remember for sure but I think I played back DRM in the Netflix app

can u tell me step by step what u did please i tried everything and dont work, im connected to server 10 as 14 not working, what server did u download?, this is what im getting so far;

C:\Users\Maverick\Desktop\L3-Dumper-main>python dump_keys.py
2021-12-29 07:02:19 PM - root - 16 - INFO - Connected to MBOX
2021-12-29 07:02:19 PM - root - 17 - INFO - scanning all processes for the following libraries
2021-12-29 07:02:20 PM - root - 19 - DEBUG - Process(pid=1, name="init", parameters={})
2021-12-29 07:02:20 PM - root - 19 - DEBUG - Process(pid=3101, name="ueventd", parameters={})
2021-12-29 07:02:20 PM - root - 19 - DEBUG - Process(pid=4029, name="logd", parameters={})
2021-12-29 07:02:20 PM - root - 19 - DEBUG - Process(pid=4030, name="debuggerd", parameters={})
2021-12-29 07:02:20 PM - root - 19 - DEBUG - Process(pid=4031, name="vold", parameters={})
2021-12-29 07:02:20 PM - root - 19 - DEBUG - Process(pid=4038, name="debuggerd:signaller", parameters={})
2021-12-29 07:02:20 PM - root - 19 - DEBUG - Process(pid=4083, name="healthd", parameters={})
2021-12-29 07:02:20 PM - root - 19 - DEBUG - Process(pid=4084, name="sh", parameters={})
2021-12-29 07:02:20 PM - root - 19 - DEBUG - Process(pid=4085, name="systemcontrol", parameters={})
2021-12-29 07:02:20 PM - root - 19 - DEBUG - Process(pid=4086, name="hdmi_cec", parameters={})
2021-12-29 07:02:20 PM - root - 19 - DEBUG - Process(pid=4087, name="lmkd", parameters={})
2021-12-29 07:02:20 PM - root - 19 - DEBUG - Process(pid=4088, name="servicemanager", parameters={})
2021-12-29 07:02:20 PM - root - 19 - DEBUG - Process(pid=4089, name="surfaceflinger", parameters={})
2021-12-29 07:02:20 PM - root - 19 - DEBUG - Process(pid=4096, name="FD628_Demo", parameters={})
2021-12-29 07:02:20 PM - root - 19 - DEBUG - Process(pid=4112, name="pppoe_wrapper", parameters={})
2021-12-29 07:02:20 PM - root - 19 - DEBUG - Process(pid=4113, name="imageserver", parameters={})
2021-12-29 07:02:20 PM - root - 19 - DEBUG - Process(pid=4120, name="zygote", parameters={})
2021-12-29 07:02:20 PM - root - 19 - DEBUG - Process(pid=4121, name="audioserver", parameters={})
2021-12-29 07:02:20 PM - root - 19 - DEBUG - Process(pid=4122, name="cameraserver", parameters={})
2021-12-29 07:02:20 PM - root - 19 - DEBUG - Process(pid=4123, name="drmserver", parameters={})
2021-12-29 07:02:21 PM - root - 19 - DEBUG - Process(pid=4124, name="installd", parameters={})
2021-12-29 07:02:21 PM - root - 19 - DEBUG - Process(pid=4126, name="daemonsu:mount:master", parameters={})
2021-12-29 07:02:21 PM - root - 19 - DEBUG - Process(pid=4127, name="keystore", parameters={})
2021-12-29 07:02:21 PM - root - 19 - DEBUG - Process(pid=4128, name="media.codec", parameters={})
2021-12-29 07:02:21 PM - root - 19 - DEBUG - Process(pid=4129, name="mediadrmserver", parameters={})
2021-12-29 07:02:22 PM - Helpers.Scanner - 82 - INFO - Running libwvdrmengine.so at 0xeb354000
2021-12-29 07:02:22 PM - Helpers.Scanner - 75 - DEBUG - {
    "from": "Dynamic Function",
    "message": "L3 RSA Key export function found: ulns"
}
2021-12-29 07:02:23 PM - Helpers.Scanner - 82 - INFO - Running libmediadrm.so at 0xed751000
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=4130, name="media.extractor", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=4131, name="mediaserver", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=4132, name="netd", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=4133, name="gatekeeperd", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=4136, name="daemonsu:master", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=4426, name="system_server", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=4505, name="com.android.inputmethod.latin", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=4517, name="com.android.systemui", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=4523, name="sdcard", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=4711, name="android.ext.services", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=4787, name="wpa_supplicant", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=4792, name="adbd", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=4796, name="PPPoE", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=4805, name="com.droidlogic.SubTitleService", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=4824, name="com.droidlogic.dig", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=4848, name="com.google.android.gms.persistent", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=4871, name="com.sunvell.win8launcher", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=5009, name="Droid Settings", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=5022, name="com.google.process.gapps", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=5085, name="com.google.android.gms", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=5219, name="com.android.tv.settings", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=5434, name="LOCAL&BACKUP", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=6183, name="daemonsu:10053", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=6446, name="frida-server-15.1.10-android-arm", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=6453, name="daemonsu:0", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=6457, name="logcat", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=6506, name="Chrome", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=6559, name="com.android.chrome:sandboxed_process0", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=6606, name="com.android.chrome:privileged_process0", parameters={})
2021-12-29 07:02:23 PM - root - 19 - DEBUG - Process(pid=6740, name="com.google.android.gms.unstable", parameters={})
2021-12-29 07:02:23 PM - root - 25 - INFO - Hooks completed

**Comment by Mavrick007** [comment]
UPDATE I Managed to dump keys from bitmovin.com/demos/drm :)

**Comment by 89z** [comment]
How did you do it?

**Comment by 89z** [comment]
I finally figured it out - the problem is the wvdumper output is confusing - you get an error - but if you just click LOAD after Hooks completed - then you get the keys. you don't need Magisk or anything
