### ISSUE TITLE
Maybe I'm just too stupid for this but hope for some help

### ISSUE THREAD

**Issue by Dansbo** [wvdumper/dumper#50]
I have rooted my Samsung SM-G955F and installed frida on it.

I have started frida using adb to my device and installed wvdumper on my computer using protobuf 3.20.1 and get the following when I start dump_keys.py:

c:\platform-tools\dumper>python dump_keys.py
2022-08-20 10:03:55 PM - root - 16 - INFO - Connected to SM G955F
2022-08-20 10:03:55 PM - root - 17 - INFO - scanning all processes for the following libraries
Traceback (most recent call last):
  File "c:\platform-tools\dumper\dump_keys.py", line 18, in <module>
    for process in device.enumerate_processes():
  File "C:\Users\tilde\AppData\Local\Programs\Python\Python310-32\lib\site-packages\frida\core.py", line 34, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\tilde\AppData\Local\Programs\Python\Python310-32\lib\site-packages\frida\core.py", line 118, in enumerate_processes
    return self._impl.enumerate_processes(*args, **kwargs)
frida.NotSupportedError: unable to handle 64-bit processes due to build configuration

Can anyone point me in the right direction?

**Comment by larsk2** [comment]
Yeah. Downgrade to py 3.8

**Comment by Dansbo** [comment]
> Yeah. Downgrade to py 3.8

Thanks for your quick answer. I tried that now and got essentially the same errors:

c:\platform-tools\dumper>python dump_keys.py
2022-08-20 10:43:31 PM - root - 16 - INFO - Connected to SM G955F
2022-08-20 10:43:31 PM - root - 17 - INFO - scanning all processes for the following libraries
Traceback (most recent call last):
  File "dump_keys.py", line 18, in <module>
    for process in device.enumerate_processes():
  File "C:\Users\tilde\AppData\Local\Programs\Python\Python38-32\lib\site-packages\frida\core.py", line 34, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\tilde\AppData\Local\Programs\Python\Python38-32\lib\site-packages\frida\core.py", line 118, in enumerate_processes
    return self._impl.enumerate_processes(*args, **kwargs)
frida.NotSupportedError: unable to handle 64-bit processes due to build configuration

**Comment by Dansbo** [comment]
I tried python x64 aswell to no avail

**Comment by Dansbo** [comment]
I feel like such an idiot. Did not install frida for x64 environment as my phone is running.
