### ISSUE TITLE
No module named 'Helpers' found

### ISSUE THREAD

**Issue by thejaceman** [wvdumper/dumper#57]
Not sure if the project is still being maintained or not. I did see the notice on the project page about OEMCrypto, but wasn't sure if my device would be impacted or not and decided to at least give the script a trial run. After making sure that I had all dependencies met in the requirements.txt file, I decided to give it a run. Upon execution, I received the following error:

Traceback (most recent call last):
  File "G:\PortableApps\dumper\dump_keys.py", line 6, in <module>
    from Helpers.Scanner import Scan
ModuleNotFoundError: No module named 'Helpers'

I should note that although I'm not familiar with 'Helpers' I did attempt to pip Helpers after receiving the error.
"Successfully installed Helpers-0.2.0"
Upon executing the command again, I received the same Traceback error as before.

**Comment by neooblaster** [comment]
Hello,

I encountered the issue.
My mistake was that I simply copy-paste the main Python script.
For those who encounter the issue, please be sure to `git clone` the projet.

Browse to the clone project, then `pip install -r requirements.txt` and then `python dump_key.py`.

Best regards

**Comment by eviljust** [comment]
wonder if anyone encountered this error too?

Traceback (most recent call last):
  File "C:\Users\folder\Downloads\dumper-main\dump_keys.py", line 6, in <module>
    from Helpers.Device import Device
ModuleNotFoundError: No module named 'Helpers.Device'
