### ISSUE TITLE
Frida device not found

### ISSUE THREAD

**Issue by EnthusiastAnon** [wvdumper/dumper#6]
When I run dump_keys.py I get this error

C:\Users\userVM\Desktop\dumper-main>dump_keys.py
Traceback (most recent call last):
  File "C:\Users\userVM\Desktop\dumper-main\dump_keys.py", line 14, in <module>
    device = frida.get_usb_device(0)
  File "C:\Users\userVM\AppData\Local\Programs\Python\Python39\lib\site-packages\frida__init.py", line 89, in get_usb_device
    return get_device_matching(lambda d: d.type == 'usb', timeout, **kwargs)
  File "C:\Users\userVM\AppData\Local\Programs\Python\Python39\lib\site-packages\frida__init.py", line 97, in get_device_matching
    return get_device_manager().get_device_matching(predicate, timeout, kwargs)
  File "C:\Users\userVM\AppData\Local\Programs\Python\Python39\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, kwargs)
  File "C:\Users\userVM\AppData\Local\Programs\Python\Python39\lib\site-packages\frida\core.py", line 58, in get_device_matching
    return Device(self._impl.get_device_matching(lambda d: predicate(Device(d)), raw_timeout))
frida.InvalidArgumentError: device not found

Frida server is running on phone, tried latest server, tried older server, no go.
Also tried adding timeout
device = frida.get_usb_device(1)
but doesn't work

**Comment by EnthusiastAnon** [comment]
I solved my issue by rooting the device with Magisk instead of Odin.
When rooted with Odin my device still showed L1 Widevine. With Magisk it went down to L3.
I also had to install older version of Magis for this to work on Samsung J5 2015. If anyone goes through all this trouble...

**Comment by girod2033** [comment]
> I solved my issue by rooting the device with Magisk instead of Odin. When rooted with Odin my device still showed L1 Widevine. With Magisk it went down to L3. I also had to install older version of Magis for this to work on Samsung J5 2015. If anyone goes through all this trouble...

Hi.
Tell me please:
1) Which version of Magisk?
2) Custom firmware?
3) Android version?

**Comment by EnthusiastAnon** [comment]
> > I solved my issue by rooting the device with Magisk instead of Odin. When rooted with Odin my device still showed L1 Widevine. With Magisk it went down to L3. I also had to install older version of Magis for this to work on Samsung J5 2015. If anyone goes through all this trouble...
> 
> Hi. Tell me please:
> 
>     1. Which version of Magisk?
> 
>     2. Custom firmware?
> 
>     3. Android version?

1. 21.4
2. I think not
3. 6.0.1

Also, I forgot to mention, I think it didn't work because phone was still L1. To make it L3 I went into Magisk modules and installed that liboemcrypto-disabler thingy.

**Comment by girod2033** [comment]
> > > I solved my issue by rooting the device with Magisk instead of Odin. When rooted with Odin my device still showed L1 Widevine. With Magisk it went down to L3. I also had to install older version of Magis for this to work on Samsung J5 2015. If anyone goes through all this trouble...
> > 
> > 
> > Hi. Tell me please:
> > ```
> > 1. Which version of Magisk?
> > 
> > 2. Custom firmware?
> > 
> > 3. Android version?
> > ```
> 
> 1. 21.4
> 2. I think not
> 3. 6.0.1
> 
> Also, I forgot to mention, I think it didn't work because phone was still L1. To make it L3 I went into Magisk modules and installed that liboemcrypto-disabler thingy.

Ok, thx.

**Comment by VCDEV1** [comment]
> > > I solved my issue by rooting the device with Magisk instead of Odin. When rooted with Odin my device still showed L1 Widevine. With Magisk it went down to L3. I also had to install older version of Magis for this to work on Samsung J5 2015. If anyone goes through all this trouble...
> > 
> > 
> > Hi. Tell me please:
> > ```
> > 1. Which version of Magisk?
> > 
> > 2. Custom firmware?
> > 
> > 3. Android version?
> > ```
> 
> 1. 21.4
> 2. I think not
> 3. 6.0.1
> 
> Also, I forgot to mention, I think it didn't work because phone was still L1. To make it L3 I went into Magisk modules and installed that liboemcrypto-disabler thingy.

@EnthusiastAnon Hi, Can you please say did the keys got dumped?

**Comment by EnthusiastAnon** [comment]
Unfortunately they didn't, read the other issue

**Comment by Reshiban** [comment]
Is it necessary to be rooted ?

**Edit:** Uh okay I guess thats only for this in the README, is it ?
> A few phone brands let us use the L1 keybox even after unlocking the bootloader (like Xiaomi). In this case, installation of a Magisk module called liboemcrypto-disabler is necessary.
