### ISSUE TITLE
What could be causing this error?

### ISSUE THREAD

**Issue by tbmny** [wvdumper/dumper#63]
Traceback (most recent call last):
  File "d:\Misc\dumper-main\dumper-main\dump_keys.py", line 6, in <module>
    from Helpers.Scanner import Scan
  File "d:\Misc\dumper-main\dumper-main\Helpers\Scanner.py", line 7, in <module>
    from Helpers.wv_proto2_pb2 import SignedLicenseRequest
  File "d:\Misc\dumper-main\dumper-main\Helpers\wv_proto2_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "C:\Users\Brandon\AppData\Local\Programs\Python\Python310\lib\site-packages\google\protobuf\descriptor.py", line 780, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.

**Comment by knoxitus** [comment]
+1 same error

the issue #59 solved it:
https://github.com/wvdumper/dumper/issues/59#issuecomment-1642329238
