### ISSUE TITLE
having trouble from my macbook (please see provided code)

### ISSUE THREAD

**Issue by toughguystudios** [wvdumper/dumper#65]
UPDATE: I downgraded (I believe) my version of protobuf and this is the response I am now getting. I'm using a Macbook btw:

Traceback (most recent call last):
  File "/Users/dumper-main/dump_keys.py", line 14, in <module>
    device = frida.get_usb_device()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/frida/__init__.py", line 137, in get_usb_device
    return get_device_manager().get_usb_device(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/frida/core.py", line 1178, in get_usb_device
    return self.get_device_matching(lambda d: d.type == "usb", timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/frida/core.py", line 1201, in get_device_matching
    return Device(self._impl.get_device_matching(lambda d: predicate(Device(d)), raw_timeout))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frida.InvalidArgumentError: device not found

Hi, I ran the script and received the following response, Can you tell me what it means/what went wrong and how to resolve, Thanks:

Ryans-MBP:dumper-main python3 dump_keys.py
Traceback (most recent call last):
  File "/Users/dumper-main/dump_keys.py", line 6, in <module>
    from Helpers.Scanner import Scan
  File "/Users/dumper-main/Helpers/Scanner.py", line 7, in <module>
    from Helpers.wv_proto2_pb2 import SignedLicenseRequest
  File "/Users/dumper-main/Helpers/wv_proto2_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/google/protobuf/descriptor.py", line 789, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by chengnan049** [comment]
Try this https://github.com/wvdumper/dumper/issues/59#issuecomment-1642329238

**Comment by toughguystudios** [comment]
Thank you

**Comment by yhunlu** [comment]
use this Pipfile:
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
frida = "*"
pycryptodome = "*"
protobuf = "==3.19.0"

[dev-packages]

[requires]
python_version = "3.10"
